version: '2'
services:
  fee-app:
    image: fee
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fee-postgresql:5432/Fee
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://fee-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://fee-elasticsearch:9200
  fee-postgresql:
    extends:
      file: postgresql.yml
      service: fee-postgresql
  fee-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: fee-elasticsearch
